version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - amazon-linux-extras install docker -y
      - service docker start
      - usermod -a -G docker ec2-user
      - echo Installing Java 17...
      - wget https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_linux-x64_bin.tar.gz
      - tar zxvf openjdk-17_linux-x64_bin.tar.gz
      - sudo mv jdk-17 /usr/local/
      - echo 'export PATH=/usr/local/jdk-17/bin:$PATH' >> ~/.bashrc
      - source ~/.bashrc
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      
  build:
    commands:
      - echo Build started on `date`
      - echo Test
      - ./gradlew test
      - echo Building the Docker image...
      - ./gradlew bootBuildImage --imageName=$IMAGE_REPO_NAME:$IMAGE_TAG      
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%d)
  discard-paths: yes
