app:
  file:
    path: /home/rafa/Project/sophi-storage/audios/
server:
  servlet:
    context-path: /api/
spring:
  data:
    mongodb:
      uri: mongodb://172.17.0.2:27017/sophi-ai-db
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
