app:
  file:
    path: /home/rafa/Project/sophi-storage/audios/
server:
  servlet:
    context-path: /api/
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent